### PR TITLE
Navigation panel, QsTrIds, cleanup, copyright headers

### PR DESCRIPTION
**Pull request by Jollailija**
I'm writing some UI for webview, stay tuned!

### CODE REVIEW

**Comment by Jollailija** [comment]
Okay, 619133b has the navigation panel. I also made the strings use QsTrId and it works!

**Comment by Jollailija** [comment]
Ps. may I please have write access? I won't mess git up too bad ;)

**Comment by fravaccaro** [comment]
Sure :) I added you to collaborators

**Comment by Jollailija** [comment]
Thanks :+1:

**Pull request merged**
